<?php
include '../Database/db_con.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require '../PHPMailer/src/Exception.php';
require '../PHPMailer/src/PHPMailer.php';
require '../PHPMailer/src/SMTP.php';
require('../fpdf/fpdf.php');

$data = json_decode(file_get_contents('php://input'), true);

if (isset($data['caseDetails']) && isset($data['newStatus']) && isset($data['updateReason'])) {
    $caseDetails = $data['caseDetails'];
    $newStatus = $conn->real_escape_string($data['newStatus']);
    $updateReason = $conn->real_escape_string($data['updateReason']);
    $ob_number = $caseDetails['ob_number'];

    $query = "UPDATE verified SET case_status = '$newStatus' WHERE ob_number = '$ob_number'";

    if ($conn->query($query) === TRUE) {
        $pdf_content = generate_pdf($ob_number, $caseDetails);

        $mail = new PHPMailer(true);

        try {
            // Server settings
            $mail->isSMTP();
            $mail->Host = 'smtp.gmail.com'; // Set the SMTP server to send through
            $mail->SMTPAuth = true;
            $mail->Username = 'kibetg984@gmail.com'; // SMTP username
            $mail->Password = 'qsgr ffuz syic piuz'; // SMTP password
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $mail->Port = 587;

            // Recipients
            $mail->setFrom('kibetg984@gmail.com', 'Sondu Police Station');
            $mail->addAddress($caseDetails['email']); // Add a recipient
            $mail->addStringAttachment($pdf_content, 'Case_Details.pdf');

            $mail->isHTML(true);
            $mail->Subject = 'Case Status Update';
            $mail->Body    = '
                <div style="font-family: Arial, sans-serif; color: #333;">
                    <h2>Case Status Updated</h2>
                    <p>Dear ' . $caseDetails['name'] . ',</p>
                    <p>Your case status has been updated to: ' . $newStatus . '</p>
                    <p>Reason: ' . $updateReason . '</p>
                    <p>Please find the attached PDF for more details.</p>
                    <p>Best regards,</p>
                    <p>Sondu Police Station</p>
                </div>';

            $mail->send();

            echo json_encode(['success' => true]);
        } catch (Exception $e) {
            echo json_encode(['success' => false, 'message' => $mail->ErrorInfo]);
        }
    } else {
        echo json_encode(['success' => false, 'message' => $conn->error]);
    }
} else {
    echo json_encode(['success' => false, 'message' => 'Invalid input']);
}

$conn->close();

function generate_pdf($ob_number, $case_details) {
    $pdf = new FPDF();
    $pdf->AddPage();
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->Image('images/sondu_logo.png', 10, 6, 30);
    $pdf->Cell(40);
    $pdf->Cell(110, 10, 'Verified Case Details', 0, 1, 'C');
    $pdf->Ln(20);
    $pdf->SetFont('Arial', '', 12);
    $pdf->SetTextColor(50, 50, 50);

    $pdf->Cell(50, 10, 'Case Number:', 0, 0);
    $pdf->Cell(50, 10, $case_details['case_number'], 0, 1);
    
    $pdf->Cell(50, 10, 'OB Number:', 0, 0);
    $pdf->Cell(50, 10, $ob_number, 0, 1);
    
    $pdf->Cell(50, 10, 'Name:', 0, 0);
    $pdf->Cell(50, 10, $case_details['name'], 0, 1);
    
    $pdf->Cell(50, 10, 'ID Number:', 0, 0);
    $pdf->Cell(50, 10, $case_details['id_number'], 0, 1);
    
    $pdf->Cell(50, 10, 'Mobile No:', 0, 0);
    $pdf->Cell(50, 10, $case_details['mobile_no'], 0, 1);
    
    $pdf->Cell(50, 10, 'Location:', 0, 0);
    $pdf->Cell(50, 10, $case_details['location'], 0, 1);
    
    $pdf->Cell(50, 10, 'Occurrence Date:', 0, 0);
    $pdf->Cell(50, 10, $case_details['occurence_date'], 0, 1);
    
    $pdf->Cell(50, 10, 'Occurrence Time:', 0, 0);
    $pdf->Cell(50, 10, $case_details['occurence_time'], 0, 1);
    
    $pdf->Cell(50, 10, 'Description:', 0, 0);
    $pdf->MultiCell(0, 10, $case_details['description']);
    
    $pdf->Cell(50, 10, 'Email:', 0, 0);
    $pdf->Cell(50, 10, $case_details['email'], 0, 1);

    $pdf->Ln(20);
    $pdf->SetFont('Arial', 'I', 10);
    $pdf->SetTextColor(100, 100, 100);
    $pdf->Cell(0, 10, 'Generated by Sondu Police Station', 0, 1, 'C');

    return $pdf->Output('S');
}
?>
